#!/usr/bin/env sh
H="$RUSKY"
[ "$H" = "2" ] && set -x
h="${0##*/}"
s="${0%/*/*}/$h"

[ ! -f "$s" ] && exit 0

for f in "${XDG_CONFIG_HOME:-$HOME/.config}/rusky/init.sh" "$HOME/.ruskyrc"; do
	# shellcheck disable=SC1090
	[ -f "$f" ] && . "$f"
done

[ "$H" = "0" ] && exit 0

sh -e "$s" "$@"
c=$?

[ $c != 0 ] && echo "rusky - $h script failed (code $c)"
[ $c = 127 ] && echo "rusky - command not found in PATH=$PATH"
exit $c
